/** Declaration file generated by dts-gen */

export = textarea_caret;

declare function textarea_caret(element: any, position: any, options: any): any;

declare namespace textarea_caret {
    const prototype: {
    };

}

